# Application Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: healthcare
  # Security Headers
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: secure-healthcare-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:healthcare_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080}
  
  # Actuator endpoints
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
        base-path: /actuator
    endpoint:
      health:
        show-details: when-authorized
        
# Logging Configuration
logging:
  level:
    com.healthcare: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/healthcare-app.log
    max-size: 10MB
    max-history: 30

# Custom Application Properties
app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,https://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  rate-limit:
    requests-per-minute: 100
    burst-capacity: 200
  
  security:
    password-policy:
      min-length: 12
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true
    
    session:
      timeout: 1800 # 30 minutes
      max-concurrent: 1
  
  file-upload:
    max-size: 10MB
    allowed-types: pdf,doc,docx,jpg,jpeg,png
    virus-scan: true
  
  audit:
    enabled: true
    retention-days: 365